steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mds-provider-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mds-provider-api']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mds-provider-api'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mds-provider-api'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--service-account=mds-api-sa@kiwibot-atlas.iam.gserviceaccount.com'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars=AUTH0_DOMAIN=${_AUTH0_DOMAIN}'
      - '--set-env-vars=AUTH0_AUDIENCE=${_AUTH0_AUDIENCE}'
      - '--set-env-vars=MDS_PROVIDER_ID=${_MDS_PROVIDER_ID}'
      - '--set-env-vars=API_BASE_URL=${_API_BASE_URL}'
      - '--set-env-vars=BIGQUERY_PROJECT_ID=${_BIGQUERY_PROJECT_ID}'
      - '--set-env-vars=CORS_ORIGINS=*'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=API_KEY_WASHINGTON_DDOT=${_API_KEY_WASHINGTON_DDOT}'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--timeout=300'

substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'mds-provider-api'
  _AUTH0_DOMAIN: 'kiwibot.auth0.com'
  _AUTH0_AUDIENCE: 'https://mds.kiwibot.com'
  _MDS_PROVIDER_ID: 'kiwibot-delivery-robots'
  _API_BASE_URL: 'https://mds.kiwibot.com'
  _BIGQUERY_PROJECT_ID: 'kiwibot-atlas'
  _API_KEY_WASHINGTON_DDOT: 'mds_washington_ddot_2024:washingtonddot:read_vehicles_read_trips_read_events'
