[project]
name = "mds-provider-api"
version = "0.1.0"
author = "Jonathan Deiloff"
description = "It offers last mile delivery robots data following MDS specs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
